version: "3.8"

services:
  node-api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ml-service

  ml-service:
    build: ../ml-service
    ports:
      - "8000:8000"
